### PR TITLE
Fix typo when requesting path to spotdl.py

### PR DESCRIPTION
**Pull request by ritiek**
I just happened to notice this.

### CODE REVIEW

**Comment by linusg** [comment]
At least someone is still using it or looking at the code :innocent:
I'll try to do both next year. Had not continued working on it for various reasons.

Thanks for the report and best wishes for 2018 @ritiek!

**Comment by ritiek** [comment]
No problem! I still need to get myself familiar with yarn.

Best wishes to you too! :grinning:

**Comment by ritiek** [comment]
And thank you for the invitation!

**Comment by linusg** [comment]
...as I had to do, as a long term and convinces `npm` user. I just added you as a collaborator here, don't feel like you have to help out here with anything, but you probably should be able merging such things. And of course you may help if you wish.

**Comment by ritiek** [comment]
I'll try to help whenever and wherever I can. Thanks once again!

**Comment by linusg** [comment]
Sure, no problem. Please don't force yourself to anything, I certainly know you have other great repos around on GitHub to maintain and are busy in general. But after all I trust you and it's based on `spotify-downloader` where you have the most knowledge of, sooo... not a bad thing to have you in here :sunglasses:

**Pull request merged**
